### ISSUE TITLE
Installation error (Build setup)

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/rt-mbms-examples#2]
I got stuck after executing this:
 cd rt-mbms-examples/flute-ffmpeg
mkdir build && cd build
cmake -GNinja ..

I got this error:
CMake Error at lib/CMakeLists.txt:1 (add_subdirectory):
  add_subdirectory given source "rt-libflute" which is not an existing
  directory.

Not sure if related but the installation of rt-libflute is cloning  "libflute" 
cd ~
git clone https://github.com/5G-MAG/libflute.git

rather than "rt-libflute"

Thanks!

**Comment by jordijoangimenez** [comment]
I've cloned libflute.git and move the folder inside rt-mbms-examples/flute-ffmpeg/lib

The cmake works

**Comment by dsilhavy** [comment]
@jordijoangimenez Thanks for reporting this. I think we need to move https://github.com/5G-MAG/rt-mbms-examples/blob/development/flute-ffmpeg/.gitmodules to the main folder of this repo. I will check this on my end

**Comment by dsilhavy** [comment]
Fixed in #11
